name: money_wallet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  path: ^1.8.3
  slide_to_confirm: ^1.1.0
  google_fonts: ^4.0.4
  salomon_bottom_bar: ^3.3.2
  number_display: ^3.0.0
  flutter_echarts: ^2.4.0
  sqflite: ^2.2.8+2
  flutter_feather_icons: ^2.0.0+1
  action_slider: ^0.6.1
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
